### PR TITLE
removes the loading spinner from the portal

### LINKED ISSUE #178: Bug: Fix the never ending loading progress bar in V2 -tst environment
**Describe the bug**
There's a never ending loading progress bar on the V2 -tst environment' s page. It appears at the bottom of the page, in a distorted way,

**To Reproduce**
1. Go to https://developer.microsoft-tst.com/en-us/graph/graph-explorer-v2/preview?1&setvar=routegraph:https://nghia4:20444
2. Let the page load
3. Scroll down the page
4. You'll see the loading progress bar

**Expected behavior**
The loading progress bar should disappear as soon as the contents load.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome and Edge]
 - Version []

**Additional context**

### PR DESCRIPTION
**Pull request by cwahome**
## Overview
The loading spinner on the portal does not stop spinning even after the app loads.

Now we check the existence of the html tag `<api-explorer>` that houses the loading spinner on the portal website and remove it from the DOM once Graph explorer is loaded

Fixes #178 

## Testing Instructions

* Log on to the tst environment
* Observe a "starting microsoft graph explorer" spinner
* Notice that it is removed from view after loading is complete

### CODE REVIEW

File: src/index.tsx [hunk 1]
```diff
@@ -26,12 +26,18 @@ import { loadGETheme } from './themes';
...
+// removes the loading spinner from GE html after the app is loaded
 const spinner = document.getElementById('spinner');
-
 if (spinner !== null) {
   (spinner as any).parentElement.removeChild(spinner);
 }
 
+// removes the loading spinner from the portal team html after GE loads
+const apiExplorer = document.getElementsByTagName('api-explorer')[0];
+if (apiExplorer && apiExplorer !== null) {
```
Comment (jobala) [inline src/index.tsx]: Why do you have to check explicitly that apiExplorer is not equal to null?

Comment (cwahome) [reply src/index.tsx]: I don't.. Was being super safe

Comment (jobala) [reply src/index.tsx]: It's unnecessary, `if (apiExplorer) {..}` should be enough.
